name: tests
on:
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

      - name: Merge PR on success
        if: success()
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO="${{ github.repository }}"
          NUMBER="${{ github.event.number }}"
          MERGE_COMMIT_TITLE="Automatically Merged by GitHub Actions"

          # Set up Git configuration
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Fetch the pull request branch
          git fetch origin pull/${NUMBER}/head:pr-${NUMBER}
          git checkout pr-${NUMBER}

          # Merge with the main branch
          git merge --no-ff origin/main -m "${MERGE_COMMIT_TITLE}"

          # Push the changes back to the pull request branch
          git push origin pr-${NUMBER}

          # Create a pull request to merge the changes
          gh pr merge ${NUMBER} --squash --title "${MERGE_COMMIT_TITLE}" --body "Automatically merged by GitHub Actions" --reviewer <REVIEWER_USERNAME>

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
